### ISSUE TITLE
Clarifications about ENTSO-E SO&AF

### ISSUE THREAD

**Issue by matteodefelice** [Open-Power-System-Data/national_generation_capacity#4]
I was wondering what is exactly the source used for the data labelled as ENTSO-E SO&AF. Considering that now the SO&AF has been replaced by MAF, is the data for SO&AF this one: https://docs.entsoe.eu/dataset/scenario-outlook-adequacy-forecast-so-af-2015/resource/380c650a-c422-45b4-98a9-5ec4f36787d9 ? 
I was analysing the installed capacity of Danish coal and for the years 2015 and 2016 I find data labelled as "entsoe SO&AF" but I don't know where to get the original source. Can you help me with this?

**Comment by mariok90** [comment]
Exactly, the source which is labelled 'ENTSO-E SO&AF' (2015) is:
https://docs.entsoe.eu/dataset/scenario-outlook-adequacy-forecast-so-af-2015/resource/380c650a-c422-45b4-98a9-5ec4f36787d9

However, SO&AF only covers 2011-2015. So for 2016 data you need to rely on other data sources.
