### ISSUE TITLE
Wrong data package profile - not readable by datapackage-py

### ISSUE THREAD

**Issue by larsschellhas** [Open-Power-System-Data/national_generation_capacity#7]
The Data packages for conventional power plants and national generation capacity contain a wrong (non-standard-conform) data package profile.
Currently the datapackage.json says:
`"profile": "tabular_data_package"`
but it should say
` "profile": "tabular-data-package"`
as can be found in the [standard specification](https://frictionlessdata.io/specs/tabular-data-package/#specification).

Because of this typo the package cannot be opened by the python library for data packages.

**Comment by weibezahn** [comment]
data package profile corrected in master branch
